FROM python:3.6
MAINTAINER Sirack Hailu

ENV PYTHON_VER 3.6.2

# copy peoject files, iteratively 
COPY . /opt/multiscanner 
# copy configuration files
COPY ./docker_utils/*.ini /opt/multiscanner/

WORKDIR /opt/multiscanner
RUN ./install.sh

# Run script
# The sleep is a workaround to make extra sure that
# the ElasticSearch container is up before the api
# attempts to connect to it
CMD sleep 30; python utils/api.py
