FROM python:3.6
MAINTAINER Sirack Hailu

ENV PYTHON_VER 3.6.2

COPY . /opt/multiscanner
COPY ./docker_utils/*.ini /opt/multiscanner/

# Install requirements for Python
curl -k https://bootstrap.pypa.io/get-pip.py | python
pip install flask 
pip install flask_cors

WORKDIR /opt/multiscanner
# RUN ./install.sh
pip install flask 
pip install flask_cors

# Run script
CMD python web/app.py
